### ISSUE TITLE
Rather use GET instead of POST if no data is actually modified

### ISSUE THREAD

**Issue by pbek** [studo-app/campus-qr#40]
As follow up for https://github.com/studo-app/campus-qr/commit/8fe8c63b1dc0ff4ec493bb816a2666bf59f6c16b#r42883335 and #35.

It would be better to use GET instead of POST if no data is actually modified in https://github.com/studo-app/campus-qr/blob/21a9300d3e2be1457dabd6753fd6bc840c90e2f9/src/serverMain/kotlin/com/studo/campusqr/Server.kt#L129-L130

**Comment by vonox7** [comment]
Due to various versions of the HTTP specification how GET body should be treated (see also https://stackoverflow.com/questions/978061/http-get-with-request-body ), i think sticking to POST requests is better. For "list" definitely, for listActiveCheckIns it is open for discussion what HTTP-method should be used. Note that we might extend this call in the future also with JSON-parameters.
Also please note that having a 100% RESTful API is not a goal of Campus QR.

**Comment by pbek** [comment]
Ok, let's stick with POST.
